using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using HiddenHarbours.Art;
using HiddenHarbours.Art.Editor;

namespace HiddenHarbours.Tests.Art.EditMode
{
    /// <summary>
    /// Content validation for the generated <see cref="DriftWeedKit"/> — the table that connects the
    /// painted drift-weed art to the running beds.
    ///
    /// <para>The failure this exists to catch is a <b>stale table</b>. The kit is generated by
    /// <see cref="DriftWeedKitBuilder"/> from the art's own sidecar; if the art director re-drops the
    /// kit and nobody re-runs the builder, the asset still loads, still has 42 entries, and still
    /// renders — with the wrong sizes against the wrong sprites. Nothing downstream would say so, the
    /// weed would just look subtly wrong. So this asserts the table against the sidecar's own
    /// provenance hash and against the drawn sizes, restated here as literals ON PURPOSE (the
    /// <c>CharacterRigBakeTests</c> convention: the duplication is what makes it an independent
    /// check).</para>
    /// </summary>
    public class DriftWeedKitContentTests
    {
        /// <summary>Kit shape from the sidecar: species → the sizes (m) its variants were drawn at.</summary>
        static readonly (string species, float[] sizes)[] Expected =
        {
            ("Bladderwrack", new[] { 0.9f, 1.25f, 0.6f, 1.05f }),
            ("SugarKelp",    new[] { 1.6f, 2.0f, 1.1f }),
            ("Eelgrass",     new[] { 0.7f, 0.9f, 0.45f, 0.8f }),
            ("TornMat",      new[] { 1.4f, 2.0f, 1.15f }),
        };

        const int RampRows = 3;

        static DriftWeedKit LoadKit()
        {
            var kit = AssetDatabase.LoadAssetAtPath<DriftWeedKit>(DriftWeedKitBuilder.KitAssetPath);
            Assert.IsNotNull(kit,
                $"No DriftWeedKit at '{DriftWeedKitBuilder.KitAssetPath}'. Run " +
                "Hidden Harbours ▸ Art ▸ Build Drift Weed Kit (after Slice Drift Weed Sheets).");
            return kit;
        }

        [Test]
        public void Kit_HasEveryClumpTheSidecarDeclares()
        {
            var kit = LoadKit();

            Assert.AreEqual(Expected.Sum(e => e.sizes.Length) * RampRows, kit.Count,
                "14 variants × 3 ramp rows = 42 clumps. A different count means the art changed and " +
                "the builder was not re-run.");
            Assert.AreEqual(Expected.Select(e => e.species), kit.Species);
            Assert.AreEqual(new[] { "living", "golden", "bleached" }, kit.Ramps);
        }

        [Test]
        public void EveryEntry_HasASpriteAndADrawnSize()
        {
            var kit = LoadKit();
            for (int i = 0; i < kit.Count; i++)
            {
                var e = kit.Entries[i];
                Assert.IsNotNull(e.Sprite,
                    $"entry {i} ({SpeciesOf(kit, e)} ramp {e.RampIndex} cell {e.VariantCell}) has no " +
                    "sprite — the sheet was re-imported without re-slicing, or the kit is stale.");
                Assert.Greater(e.SizeMeters, 0f,
                    $"entry {i}: SizeMeters is {e.SizeMeters}. The drawn size is what lets the " +
                    "presenter draw at native scale; it cannot be zero.");
                Assert.GreaterOrEqual(e.SpeciesIndex, 0);
                Assert.Less(e.SpeciesIndex, kit.Species.Length);
                Assert.GreaterOrEqual(e.RampIndex, 0);
                Assert.Less(e.RampIndex, kit.Ramps.Length);
            }
        }

        [Test]
        public void EverySpecies_CarriesItsOwnDrawnSizes_OnAllThreeRampRows()
        {
            var kit = LoadKit();
            for (int s = 0; s < Expected.Length; s++)
            {
                var (species, sizes) = Expected[s];
                for (int r = 0; r < RampRows; r++)
                {
                    var got = kit.Entries.Where(e => e.SpeciesIndex == s && e.RampIndex == r)
                                         .Select(e => e.SizeMeters).OrderBy(m => m).ToArray();
                    var want = sizes.OrderBy(m => m).ToArray();
                    Assert.AreEqual(want.Length, got.Length,
                        $"{species} ramp {kit.Ramps[r]}: {got.Length} clumps, expected {want.Length}");
                    for (int i = 0; i < want.Length; i++)
                        Assert.AreEqual(want[i], got[i], 1e-4f,
                            $"{species} ramp {kit.Ramps[r]}: drawn sizes drifted from the sidecar");
                }
            }
        }

        /// <summary>
        /// The staleness tripwire. The sidecar publishes the sha of the rig it was derived from; the
        /// builder copies it into the asset. A re-drop of the art changes that sha, so a kit built
        /// against the old art fails here even though every other assertion above would still pass.
        /// </summary>
        [Test]
        public void Kit_WasBuiltFromTheSidecarCurrentlyOnDisk()
        {
            var kit = LoadKit();
            string sidecarPath = DriftWeedSheetSlicer.SidecarPath;
            Assert.IsTrue(File.Exists(sidecarPath), $"sidecar missing at '{sidecarPath}'");

            var m = Regex.Match(File.ReadAllText(sidecarPath),
                                "\"derivedFromRigSha256\"\\s*:\\s*\"([0-9a-fA-F]+)\"");
            Assert.IsTrue(m.Success, "sidecar carries no derivedFromRigSha256 to check against");

            Assert.AreEqual(m.Groups[1].Value, kit.BuiltFromRigSha256,
                "The kit was built from a DIFFERENT drift-weed rig than the sidecar on disk. The art " +
                "was re-dropped without re-running Hidden Harbours ▸ Art ▸ Build Drift Weed Kit, so " +
                "the table's sizes and sprites no longer describe the sheets.");
        }

        // ---- the beds ---------------------------------------------------------------------------

        [Test]
        public void EverySeaweedBed_PointsAtTheKit_SoNoBedIsStillGreybox()
        {
            var kit = LoadKit();
            var defs = AssetDatabase.FindAssets($"t:{nameof(SeaweedDef)}", new[] { "Assets/_Project/Data" })
                                    .Select(g => AssetDatabase.LoadAssetAtPath<SeaweedDef>(
                                                     AssetDatabase.GUIDToAssetPath(g)))
                                    .Where(d => d != null).ToList();
            Assert.IsNotEmpty(defs, "the working coast ships at least one SeaweedDef");

            foreach (var def in defs)
                Assert.AreSame(kit, def.WeedArt,
                    $"{def.name} has no painted art, so its whole bed renders as greybox blobs. Run " +
                    "the kit builder (it points any unwired bed at the kit), or set WeedArt by hand " +
                    "if this bed is deliberately greybox.");
        }

        /// <summary>
        /// Every tier a bed asks for must be servable by art drawn near that size — otherwise the
        /// presenter picks the closest clump it can and the reader sees a clump that is visibly the
        /// wrong size for its tier. 0.34 relative is the loosest gap the shipped ladder produces.
        /// </summary>
        [Test]
        public void EveryBedTier_CanBeServedByArtDrawnNearThatSize()
        {
            var kit = LoadKit();
            var sizes = kit.Entries.Select(e => e.SizeMeters).ToArray();

            foreach (string guid in AssetDatabase.FindAssets($"t:{nameof(SeaweedDef)}",
                                                             new[] { "Assets/_Project/Data" }))
            {
                var def = AssetDatabase.LoadAssetAtPath<SeaweedDef>(AssetDatabase.GUIDToAssetPath(guid));
                if (def == null || def.WeedArt == null || def.TierSizesMeters == null) continue;

                foreach (float tier in def.TierSizesMeters)
                {
                    float nearest = sizes.OrderBy(s => Mathf.Abs(s - tier)).First();
                    float rel = Mathf.Abs(nearest - tier) / Mathf.Max(0.01f, tier);
                    Assert.LessOrEqual(rel, 0.34f,
                        $"{def.name}: tier {tier} m has no clump drawn near it (nearest {nearest} m, " +
                        $"{rel:P0} off). Either retune the ladder to the art or ask for a clump at " +
                        "that size — the presenter will not rescale pixel art to cover the gap.");
                }
            }
        }

        /// <summary>
        /// The end-to-end wiring, on the REAL asset: for every bed, every tier and a spread of piece
        /// keys, the selection the presenter actually runs must hand back a real painted sprite. The
        /// synthetic tests in <c>DriftWeedArtSelectionTests</c> prove the maths; this proves the maths
        /// is wired to the shipped kit's own flat views — the step where a null sprite or an empty
        /// array would quietly put every clump back on the greybox blob.
        /// </summary>
        [Test]
        public void ForEveryBedAndTier_TheShippedKitHandsBackARealPaintedSprite()
        {
            var kit = LoadKit();
            var checkedCombos = 0;

            foreach (string guid in AssetDatabase.FindAssets($"t:{nameof(SeaweedDef)}",
                                                             new[] { "Assets/_Project/Data" }))
            {
                var def = AssetDatabase.LoadAssetAtPath<SeaweedDef>(AssetDatabase.GUIDToAssetPath(guid));
                if (def == null || def.WeedArt == null) continue;

                bool[] mask = def.WeedArt.ResolveSpeciesMask(def.SpeciesFilter);
                for (int tier = 0; tier <= def.MaxTier; tier++)
                {
                    float footprint = def.TierSizesMeters[Mathf.Clamp(tier, 0,
                                          def.TierSizesMeters.Length - 1)];
                    for (int key = 0; key < 120; key++)
                    {
                        int ramp = SeaweedMath.PickRamp(def.RampWeights, kit.Ramps.Length, key);
                        int pick = SeaweedMath.PickWeedArt(footprint, kit.Sizes, kit.SpeciesIndices,
                                                           kit.RampIndices, kit.Count, mask, ramp, key);
                        Assert.GreaterOrEqual(pick, 0,
                            $"{def.name} tier {tier} ({footprint} m) key {key}: no clump selected");
                        Assert.IsNotNull(kit.Entries[pick].Sprite,
                            $"{def.name} tier {tier} key {key}: selected entry {pick} has a null sprite, " +
                            "so this piece would silently fall back to the greybox blob.");
                        checkedCombos++;
                    }
                }
            }

            Assert.Greater(checkedCombos, 0,
                "no bed/tier combination was exercised — this test proved nothing.");
        }

        [Test]
        public void SpeciesMask_ResolvesNamesLooselyButNeverEmptiesABed()
        {
            var kit = LoadKit();

            Assert.IsNull(kit.ResolveSpeciesMask(null), "no filter = every species");
            Assert.IsNull(kit.ResolveSpeciesMask(new string[0]), "empty filter = every species");
            Assert.IsNull(kit.ResolveSpeciesMask(new[] { "Nonexistent" }),
                "a filter naming only unknown species must fall back to ALL, not to none — a typo " +
                "must not silently empty a bed.");

            var mask = kit.ResolveSpeciesMask(new[] { "sugarkelp" });
            Assert.IsNotNull(mask, "names match case-insensitively");
            Assert.AreEqual(1, mask.Count(b => b));
            Assert.IsTrue(mask[System.Array.IndexOf(kit.Species, "SugarKelp")]);
        }

        static string SpeciesOf(DriftWeedKit kit, DriftWeedKit.Entry e) =>
            e.SpeciesIndex >= 0 && e.SpeciesIndex < kit.Species.Length
                ? kit.Species[e.SpeciesIndex] : "?";
    }
}
