using UnityEngine;

namespace HiddenHarbours.Tests.EditMode
{
    /// <summary>
    /// <b>ST PETERS' KEY SCENES, AS THEIR FILES RECORD THEM</b>, row by row in CD's order, for
    /// <see cref="StPetersKeyScenesContentTests"/>. Each scene's Source names the file its rows come from and pins it
    /// by its hash. The Landing and the cannery are return 2's rows as main places them (#913); their new rows land
    /// with them in wave 1b. The other seven are CD's one-scene package of 2026-10-01, read through the id map
    /// (<c>docs/design/st-peters-key-scenes/key-scene-id-map.json</c>) and, where a mount names no host by id, the
    /// hosts' table beside it: data, not placed, until their waves place them. Written from the importer's output and
    /// checked row by row against the package by a reader of its own, so a row here changes only with its file. The
    /// step reads no more of a piece than this holds; its foot, layer, walk, collider, tide window, options and
    /// lights are the importer's tests' (<see cref="KeySceneImportTests"/>).
    /// </summary>
    internal static class StPetersKeyScenesRecord
    {
        internal sealed class Scene
        {
            public readonly string Id, Source;
            public readonly bool Placed;
            public readonly string[] PlacementIds;

            public Scene(string id, bool placed, string source, string[] placementIds = null)
            {
                Id = id; Placed = placed; Source = source; PlacementIds = placementIds ?? new string[0];
            }
        }

        internal sealed class Row
        {
            public readonly string Scene, Id, Kind, Owner, Kit, Piece, State, StandsOn, MountHost, MountAnchor;
            public readonly Vector2 At;
            public readonly float Z;
            public readonly int Dir;
            public readonly float? SortY;
            public readonly string[] Variants, Words;

            public Row(string scene, string id, string kind, string kit, string piece, string state, float x, float y, float z,
                       string standsOn, int dir, float? sortY = null, string owner = "", string host = "", string anchor = "",
                       string[] variants = null, string[] words = null)
            {
                Scene = scene; Id = id; Kind = kind; Owner = owner; Kit = kit; Piece = piece; State = state;
                At = new Vector2(x, y); Z = z; StandsOn = standsOn; MountHost = host; MountAnchor = anchor; Dir = dir;
                SortY = sortY; Variants = variants ?? new[] { "today" }; Words = words ?? new string[0];
            }
        }

        internal const string AlderFall = "keyscene.stp_alder_fall",
                              Cannery = "keyscene.stp_cannery",
                              Crossing = "keyscene.stp_crossing",
                              GapBridge = "keyscene.stp_gap_bridge",
                              GinnysPlot = "keyscene.stp_ginnys_plot",
                              Landing = "keyscene.stp_landing",
                              MainBeach = "keyscene.stp_main_beach",
                              NeLight = "keyscene.stp_ne_light",
                              WhelpsLookout = "keyscene.stp_whelps_lookout";

        internal static readonly Scene[] Scenes =
        {
            new Scene("keyscene.stp_alder_fall", false, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_alder_fall/scene.json, 32326 bytes, sha256 cfdf7ca09bd48835ab3a0f2c9c9780f8a9c5ae8a974b81377fa89f93b79b7b1e", new string[] {  }),
            new Scene("keyscene.stp_cannery", true, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_cannery/scene.json, 18018 bytes, sha256 e803abdb2a08f971140e0e7b9e9d6822a53f645dc7ccf6dcd99e3c7a60ec2f71", new string[] {  }),
            new Scene("keyscene.stp_crossing", false, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_crossing/scene.json, 93787 bytes, sha256 3668d9f5d0ae81e89350222a1c2218a46a946643a1e6d734701601417555a395", new string[] {  }),
            new Scene("keyscene.stp_east_end", true, "HH-st-peters-phase-a-art-2026-10-02/east-end/eastEndPieces.json; sha256 e7cd4023be9c6819a7c1d66143ba76dfa47ad5f13ba4f8e12c90c0080c160f9a", new string[] { "structure.stp_net_loft", "structure.stp_net_shed", "prop.stp_loft_traps", "prop.stp_loft_traps_b", "prop.stp_loft_buoys", "prop.stp_loft_nets", "prop.stp_loft_wood", "prop.stp_loft_oilskins", "prop.stp_loft_barrow", "prop.stp_flake_a", "prop.stp_flake_b", "prop.stp_shed_reel", "prop.stp_shed_totes", "prop.stp_shed_baskets", "prop.stp_bait_ice", "prop.stp_bait_salt", "prop.stp_bait_bike", "prop.stp_bait_flag" }),
            new Scene("keyscene.stp_gap_bridge", false, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_gap_bridge/scene.json, 18372 bytes, sha256 f8a2c1a73d422b54ede4fa2967b314388cf7a1d4ebd05352d5f05f5d780e2a89", new string[] {  }),
            new Scene("keyscene.stp_ginnys_plot", false, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_ginnys_plot/scene.json, 74708 bytes, sha256 485295444d40fdb2ca4811f1a1423591fda601646a6980f075332fc71e456edb", new string[] {  }),
            new Scene("keyscene.stp_landing", true, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_landing/scene.json, 19211 bytes, sha256 0ec0da53ccf7f2a55a2f40697fa7fe6ec26e809c3ef4ed63a1ac6f1be5cdebd4", new string[] {  }),
            new Scene("keyscene.stp_main_beach", false, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_main_beach/scene.json, 14731 bytes, sha256 5038d430dbb07cf5dcff89e399646ed98c531b9c0917f4baac7b5737ff118c27", new string[] {  }),
            new Scene("keyscene.stp_ne_light", false, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_ne_light/scene.json, 36010 bytes, sha256 d9fec2ce6df52908432c0b88cc9cff7be21436fe7e61e5e551eea15c4060e901", new string[] {  }),
            new Scene("keyscene.stp_whelps_lookout", true, "HH-st-peters-one-scene-package-2026-10-01, scenes/keyscene.stp_whelps_lookout/scene.json, 51709 bytes, sha256 6da6a6029654821458c47d2702c855b6c013b16148a14e9671d9a8b5097225f4", new string[] { "prop.stp_whelps_lookout_bench" }),
        };

        internal static readonly Row[] Rows =
        {
            // keyscene.stp_alder_fall
            new Row("keyscene.stp_alder_fall", "fall.stp_alder_fall", "waterfall", "alderFall", "fallfx", "", 106.22f, 61.32f, 2.05f, "mount", 0, null, "", "pond.stp_alder_plunge", "surface", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_flat_stone", "rock", "pxRockIso3", "rock", "", 103.85f, 63.5f, 2.16f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "prop.stp_af_tin_cup", "setPiece", "afPieces", "tinCup", "", 103.98f, 63.44f, 2.33f, "mount", 1, null, "", "rock.stp_af_flat_stone", "top", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_stepping_stone_1", "rock", "pxRockIso3", "rock", "", 104.55f, 63.95f, 2.07f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_stepping_stone_2", "rock", "pxRockIso3", "rock", "", 105.15f, 64.26f, 2.11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_stepping_stone_3", "rock", "pxRockIso3", "rock", "", 105.8f, 64.5f, 2f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_stepping_stone_4", "rock", "pxRockIso3", "rock", "", 106.45f, 64.36f, 2.07f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_stepping_stone_5", "rock", "pxRockIso3", "rock", "", 107.05f, 64.06f, 2f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_chute_1", "rock", "pxRockIso3", "rock", "", 105.35f, 65.35f, 1.82f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_chute_2", "rock", "pxRockIso3", "rock", "", 106.05f, 65.9f, 1.67f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_chute_3", "rock", "pxRockIso3", "rock", "", 105.05f, 66.75f, 1.17f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_chute_4", "rock", "pxRockIso3", "rock", "", 105.7f, 67.35f, 0.9f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_lip_bed_w", "rock", "pxRockIso3", "rock", "", 104.75f, 60.85f, 2.92f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_lip_bed_e", "rock", "pxRockIso3", "rock", "", 107.85f, 61.15f, 3.21f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "rock.stp_af_east_block", "rock", "pxRockIso3", "rock", "", 108.25f, 63f, 2.36f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "prop.stp_af_fallen_alder", "setPiece", "afPieces", "fallenAlder", "", 105.65f, 66.25f, 1.39f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_speckled_alder_01", "plant", "plantIsoRig5", "SpeckledAlder", "", 110.9f, 56.4f, 5.61f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_ostrich_fern_01", "plant", "plantIsoRig5", "OstrichFern", "", 103.95f, 62.2f, 2.34f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_ostrich_fern_02", "plant", "plantIsoRig5", "OstrichFern", "", 108.35f, 62.35f, 2.65f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_ostrich_fern_03", "plant", "plantIsoRig5", "OstrichFern", "", 104.3f, 65.3f, 1.83f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_ostrich_fern_04", "plant", "plantIsoRig5", "OstrichFern", "", 107.2f, 65.1f, 2.1f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_ostrich_fern_05", "plant", "plantIsoRig5", "OstrichFern", "", 103.5f, 60.7f, 3.54f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_ostrich_fern_06", "plant", "plantIsoRig5", "OstrichFern", "", 109f, 61.2f, 4.1f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_marsh_marigold_01", "plant", "plantIsoRig5", "MarshMarigold", "", 104.95f, 61.75f, 1.63f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_marsh_marigold_02", "plant", "plantIsoRig5", "MarshMarigold", "", 107.45f, 61.95f, 1.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_marsh_marigold_03", "plant", "plantIsoRig5", "MarshMarigold", "", 104.25f, 63.25f, 2.06f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_marsh_marigold_04", "plant", "plantIsoRig5", "MarshMarigold", "", 107.8f, 63.7f, 2.11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_marsh_marigold_05", "plant", "plantIsoRig5", "MarshMarigold", "", 105.35f, 60.4f, 4f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_marsh_marigold_06", "plant", "plantIsoRig5", "MarshMarigold", "", 107.2f, 60.55f, 4.1f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_soft_rush_01", "plant", "plantIsoRig5", "SoftRush", "", 105.05f, 64.85f, 2.15f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_soft_rush_02", "plant", "plantIsoRig5", "SoftRush", "", 106.75f, 64.95f, 2.16f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_blue_flag_01", "plant", "plantIsoRig5", "BlueFlag", "", 107.55f, 56.7f, 5.1f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_blue_flag_02", "plant", "plantIsoRig5", "BlueFlag", "", 106.05f, 57.3f, 5.01f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_speckled_alder_02", "plant", "plantIsoRig5", "SpeckledAlder", "", 107.8f, 66.95f, 1.1f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_alder_fall", "plant.stp_af_speckled_alder_03", "plant", "plantIsoRig5", "SpeckledAlder", "", 103.05f, 56.75f, 5.61f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_cannery
            new Row("keyscene.stp_cannery", "structure.stp_cannery", "building", "wharfBuilding2", "cannery", "", 170f, 16f, 6f, "ground", 5, null, "StPetersCannery", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "structure.stp_cannery_restored", "building", "wharfBuilding2", "cannery", "", 170f, 16f, 6f, "ground", 5, null, "", "", "", new string[] { "restored" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "structure.stp_cannery_boiler_stack", "setPiece", "stPetersSetPieces", "boilerStack", "", 173.32f, 22.15f, 6f, "ground", 7, 16.4f, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "structure.stp_cannery_boiler_stack_restored", "setPiece", "stPetersSetPieces", "boilerStack", "", 173.32f, 22.15f, 6f, "ground", 7, 16.4f, "", "", "", new string[] { "restored" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "structure.stp_cannery_trolley_line", "setPiece", "stPetersSetPieces", "trolleyLine", "", 175.59f, 9.57f, 6f, "ground", 0, 12f, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "structure.stp_cannery_trolley_line_restored", "setPiece", "stPetersSetPieces", "trolleyLine", "", 175.59f, 9.57f, 6f, "ground", 0, 12f, "", "", "", new string[] { "restored" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_trolley", "setPiece", "stPetersSetPieces", "trolley", "", 178f, 6.9f, 6f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_trolley_restored", "setPiece", "stPetersSetPieces", "trolley", "", 180.9f, 3.6f, 6f, "ground", 7, null, "", "", "", new string[] { "restored" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_conveyor", "setPiece", "stPetersSetPieces", "conveyor", "", 168.3f, 9.21f, 6f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_conveyor_restored", "setPiece", "stPetersSetPieces", "conveyor", "", 168.3f, 9.21f, 6f, "ground", 3, null, "", "", "", new string[] { "restored" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_fallen_sign", "setPiece", "stPetersSetPieces", "fallenSign", "", 166.6f, 5.4f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] { "words.cannery_sign" }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_door_notice", "setPiece", "stPetersSetPieces", "doorNotice", "", 175.52f, 10.48f, 7.2f, "mount", 5, 10.5f, "", "structure.stp_cannery", "door", new string[] { "today" }, new string[] { "words.cannery_notice" }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_net_rack", "setPiece", "wharfDecor", "netFrame", "", 180.2f, 12.6f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_broken_boxes", "setPiece", "wharfDecor", "crateStack", "", 172.6f, 8.4f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_drum", "setPiece", "wharfDecor", "oilDrum", "", 163.9f, 9.6f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_gull_a", "gull", "seagull", "perch", "", 174.38f, 11.62f, 15.3f, "mount", 4, 15.5f, "", "structure.stp_cannery", "ridge", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_gull_b", "gull", "seagull", "perch", "", 167.17f, 20.53f, 14.6f, "mount", 3, 15.5f, "", "structure.stp_cannery", "boilerHouseRidge", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_crates_restored", "setPiece", "wharfDecor", "crateStack", "", 173.6f, 9.2f, 6f, "ground", 4, null, "", "", "", new string[] { "restored" }, new string[] {  }),
            new Row("keyscene.stp_cannery", "prop.stp_cannery_totes_restored", "setPiece", "wharfDecor", "toteStack", "", 177.6f, 10f, 6f, "ground", 4, null, "", "", "", new string[] { "restored" }, new string[] {  }),
            // keyscene.stp_crossing
            new Row("keyscene.stp_crossing", "prop.stp_cx_crossing_board", "setPiece", "cxPieces", "crossingBoard", "", -52.6f, 2.3f, 5.64f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] { "words.stp_crossing_board" }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_gut_gauge", "setPiece", "cxPieces", "gutGauge", "", -74.5f, 12.2f, -0.89f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_01", "setPiece", "cxPieces", "withy", "", -60.5f, 0.91f, 2.23f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_02", "setPiece", "cxPieces", "withy", "", -72.79f, -0.31f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_03", "setPiece", "cxPieces", "withy", "", -83.89f, 0.16f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_04", "setPiece", "cxPieces", "withy", "", -95.05f, 3.64f, 0.67f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_05", "setPiece", "cxPieces", "withy", "", -106.96f, 0.92f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_06", "setPiece", "cxPieces", "withy", "", -118.97f, -2.26f, 0.78f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_07", "setPiece", "cxPieces", "withy", "", -131.25f, 1.92f, 0.81f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_08", "setPiece", "cxPieces", "withy", "", -142.04f, 1.29f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_09", "setPiece", "cxPieces", "withy", "", -153.32f, -2.09f, 0.8f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_10", "setPiece", "cxPieces", "withy", "", -164.77f, 0.85f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_11", "setPiece", "cxPieces", "withy", "", -176.04f, 2.54f, 0.76f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_12", "setPiece", "cxPieces", "withy", "", -186.79f, -1.3f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_13", "setPiece", "cxPieces", "withy", "", -198.3f, 0.94f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_14", "setPiece", "cxPieces", "withy", "", -210.12f, 1.63f, 0.83f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_15", "setPiece", "cxPieces", "withy", "", -227.1f, 0.9f, 0.06f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_16", "setPiece", "cxPieces", "withy", "", -234.1f, 0.9f, -0.59f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_17", "setPiece", "cxPieces", "withy", "", -241.1f, 0.9f, 0.05f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_18", "setPiece", "cxPieces", "withy", "", -247.2f, 0.87f, 0.81f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_19", "setPiece", "cxPieces", "withy", "", -260.31f, 0.8f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_20", "setPiece", "cxPieces", "withy", "", -272.69f, 0.16f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_21", "setPiece", "cxPieces", "withy", "", -284.09f, 0.66f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_22", "setPiece", "cxPieces", "withy", "", -296.28f, 4.01f, 0.65f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_23", "setPiece", "cxPieces", "withy", "", -307.91f, 0.42f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_24", "setPiece", "cxPieces", "withy", "", -319.67f, 0.15f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_25", "setPiece", "cxPieces", "withy", "", -331.32f, 0.88f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_withy_26", "setPiece", "cxPieces", "withy", "", -343.93f, 0.93f, 0.86f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "structure.stp_cx_refuge", "setPiece", "cxPieces", "refugeHut", "", -250f, 4.6f, 0.57f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] { "words.stp_refuge_name" }),
            new Row("keyscene.stp_crossing", "structure.stp_cx_wreck", "setPiece", "cxPieces", "wreck", "", -168f, -13.8f, -1.34f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_lost_pot", "setPiece", "cxPieces", "lostPot", "", -240.5f, -11.6f, -0.75f, "ground", 1, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_clam_hod", "setPiece", "ginnyPieces", "clamHod", "", -71.6f, -12.9f, -1.02f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_clam_rake", "setPiece", "ginnyPieces", "rakes", "", -70.9f, -13.25f, -0.92f, "ground", 7, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_01", "setPiece", "cxPieces", "sandpiper", "", -100.95f, -17.12f, -2.09f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_02", "setPiece", "cxPieces", "sandpiper", "", -100.26f, -17.54f, -2.17f, "ground", 6, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_03", "setPiece", "cxPieces", "sandpiper", "", -99.79f, -16.61f, -1.95f, "ground", 7, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_04", "setPiece", "cxPieces", "sandpiper", "", -130.11f, -15.95f, -1.87f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_05", "setPiece", "cxPieces", "sandpiper", "", -131.09f, -17.25f, -2.21f, "ground", 6, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_06", "setPiece", "cxPieces", "sandpiper", "", -130.9f, -17.12f, -2.18f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_07", "setPiece", "cxPieces", "sandpiper", "", -130.49f, -17.18f, -2.18f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_08", "setPiece", "cxPieces", "sandpiper", "", -130.03f, -15.9f, -1.89f, "ground", 2, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_09", "setPiece", "cxPieces", "sandpiper", "", -155.92f, -16.74f, -2f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_10", "setPiece", "cxPieces", "sandpiper", "", -156.21f, -15.25f, -1.64f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_11", "setPiece", "cxPieces", "sandpiper", "", -156.5f, -15.78f, -1.77f, "ground", 7, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_12", "setPiece", "cxPieces", "sandpiper", "", -156.16f, -16.24f, -1.85f, "ground", 0, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_13", "setPiece", "cxPieces", "sandpiper", "", -200.15f, -15.33f, -1.49f, "ground", 4, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_14", "setPiece", "cxPieces", "sandpiper", "", -200.43f, -16.31f, -1.72f, "ground", 0, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_15", "setPiece", "cxPieces", "sandpiper", "", -201.67f, -17.44f, -1.97f, "ground", 0, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_16", "setPiece", "cxPieces", "sandpiper", "", -201.08f, -16.57f, -1.77f, "ground", 2, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_17", "setPiece", "cxPieces", "sandpiper", "", -201.66f, -16.97f, -1.86f, "ground", 7, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_18", "setPiece", "cxPieces", "sandpiper", "", -211.29f, -15.76f, -1.74f, "ground", 3, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_19", "setPiece", "cxPieces", "sandpiper", "", -211.27f, -15.46f, -1.66f, "ground", 4, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_20", "setPiece", "cxPieces", "sandpiper", "", -210.17f, -15.9f, -1.7f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_21", "setPiece", "cxPieces", "sandpiper", "", -210.58f, -16.26f, -1.81f, "ground", 4, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_22", "setPiece", "cxPieces", "sandpiper", "", -259.67f, -16.82f, -2.16f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_23", "setPiece", "cxPieces", "sandpiper", "", -259.17f, -15.94f, -1.93f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_24", "setPiece", "cxPieces", "sandpiper", "", -259.96f, -15.77f, -1.91f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_25", "setPiece", "cxPieces", "sandpiper", "", -293.76f, -15.46f, -1.97f, "ground", 0, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_26", "setPiece", "cxPieces", "sandpiper", "", -294.41f, -15.55f, -1.98f, "ground", 6, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_27", "setPiece", "cxPieces", "sandpiper", "", -294.08f, -16.59f, -2.24f, "ground", 4, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_28", "setPiece", "cxPieces", "sandpiper", "", -294.16f, -17.65f, -2.49f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_29", "setPiece", "cxPieces", "sandpiper", "", -294.53f, -16.65f, -2.25f, "ground", 0, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_30", "setPiece", "cxPieces", "sandpiper", "", -327.5f, -16.59f, -1.66f, "ground", 2, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_31", "setPiece", "cxPieces", "sandpiper", "", -326.74f, -15.98f, -1.51f, "ground", 2, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_32", "setPiece", "cxPieces", "sandpiper", "", -326.74f, -15.56f, -1.41f, "ground", 1, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_33", "setPiece", "cxPieces", "sandpiper", "", -327.03f, -16.74f, -1.7f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "prop.stp_cx_sandpiper_34", "setPiece", "cxPieces", "sandpiper", "", -326.81f, -15.82f, -1.48f, "ground", 0, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_wreck_stem", "gull", "seagull", "perch", "", -162.38f, -12.37f, 0.22f, "mount", 5, null, "", "structure.stp_cx_wreck", "stem", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_mussels_a", "gull", "seagull", "perch", "", -229.2f, 13.4f, -1.17f, "ground", 2, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_mussels_b", "gull", "seagull", "perch", "", -226.8f, 14.1f, -1.34f, "ground", 5, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_mussels_c", "gull", "seagull", "perch", "", -243.5f, -13.2f, -1.13f, "ground", 6, null, "", "", "", new string[] { "low" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_flats_a", "gull", "seagull", "perch", "", -80.5f, -6.2f, 0.34f, "ground", 3, null, "", "", "", new string[] { "low", "open" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_flats_b", "gull", "seagull", "perch", "", -65.8f, 8.4f, -0.06f, "ground", 6, null, "", "", "", new string[] { "low", "open" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_crest_mid", "gull", "seagull", "perch", "", -181.5f, 3.2f, 0.71f, "ground", 1, null, "", "", "", new string[] { "open" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_crest_gut", "gull", "seagull", "perch", "", -221f, -2.4f, 0.72f, "ground", 6, null, "", "", "", new string[] { "open" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_float_1", "gull", "seagull", "perch", "", -83f, 5.5f, 0.31f, "water", 2, null, "", "", "", new string[] { "high" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_float_2", "gull", "seagull", "perch", "", -72.5f, -9f, -0.18f, "water", 6, null, "", "", "", new string[] { "high" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_float_3", "gull", "seagull", "perch", "", -178f, 6.5f, 0.5f, "water", 1, null, "", "", "", new string[] { "high" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_float_4", "gull", "seagull", "perch", "", -160f, -4.5f, 0.59f, "water", 5, null, "", "", "", new string[] { "high" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_float_5", "gull", "seagull", "perch", "", -231f, 7.5f, -0.52f, "water", 3, null, "", "", "", new string[] { "high" }, new string[] {  }),
            new Row("keyscene.stp_crossing", "gull.stp_cx_float_6", "gull", "seagull", "perch", "", -238f, -5.2f, -0.41f, "water", 7, null, "", "", "", new string[] { "high" }, new string[] {  }),
            // keyscene.stp_east_end
            new Row("keyscene.stp_east_end", "structure.stp_net_loft", "building", "wharfBuilding2", "redShed", "", 183.2f, 22.8f, 5.8907366f, "ground", 6, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "structure.stp_net_shed", "building", "wharfBuilding2", "netShed", "", 187.7f, 9.3f, 5.9999084f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "structure.stp_ice_house", "building", "wharfBuilding2", "iceHouse", "", 158.6f, 7.6f, 5.9999084f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_traps", "setPiece", "wharfDecor", "trapStack", "", 185.3f, 20.5f, 5.61872f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_traps_b", "setPiece", "wharfDecor", "trapStack", "", 186.1f, 21.6f, 4.9786916f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_buoys", "setPiece", "wharfDecor", "buoyRack", "", 180.6f, 21f, 5.9999084f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_nets", "setPiece", "wharfDecor", "netPile", "", 185.2f, 24.4f, 4.740137f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_wood", "setPiece", "wharfDecor", "woodStack", "", 180.4f, 25.2f, 5.9644203f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_oilskins", "setPiece", "wharfDecor", "oilskinLine", "", 179.2f, 22.6f, 5.9999084f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_loft_barrow", "setPiece", "wharfDecor", "wheelbarrow", "", 186.8f, 19.4f, 5.1399226f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_flake_a", "setPiece", "wharfDecor", "codFlake", "", 178f, 26.6f, 5.9941587f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_flake_b", "setPiece", "wharfDecor", "codFlake", "", 175.2f, 29f, 5.9784727f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_shed_reel", "setPiece", "wharfDecor", "netReel", "", 189.9f, 7.3f, 5.82554f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_shed_totes", "setPiece", "wharfDecor", "toteStack", "", 185.6f, 7.8f, 5.9999084f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_shed_baskets", "setPiece", "wharfDecor", "bushelBaskets", "", 186.6f, 6.6f, 5.8830423f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_bait_ice", "setPiece", "wharfDecor", "iceChest", "", 184.9f, -7.1f, 5.9999084f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_bait_salt", "setPiece", "wharfDecor", "saltBin", "", 184.4f, -5.8f, 5.9959526f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_bait_bike", "setPiece", "wharfDecor", "bicycle", "", 179.9f, -6.4f, 5.9999084f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_bait_flag", "setPiece", "wharfDecor", "flagpole", "", 179.6f, -11.4f, 5.9999084f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_ice_wood", "setPiece", "wharfDecor", "woodStack", "", 156.7f, 5.4f, 5.999601f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_east_end", "prop.stp_ice_barrow", "setPiece", "wharfDecor", "wheelbarrow", "", 161.1f, 4.6f, 5.9999084f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_gap_bridge
            new Row("keyscene.stp_gap_bridge", "structure.stp_gap_bridge", "setPiece", "stpXpPieces", "plankBridge", "", 156.45f, -40.95f, 5.28f, "mount", 1, null, "", "ground.stp_gap_bridge", "footings", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_gap_bridge", "rock.stp_gap_dipping_stone", "rock", "pxRockIso3", "slab", "", 157.95f, -41.53f, 5.1f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_ginnys_plot
            new Row("keyscene.stp_ginnys_plot", "building.stp_ginny_cottage", "building", "houseIso", "ginnyCottage", "", 84f, 28f, 6f, "ground", 2, null, "StPetersGinnyPlot", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "home.ginny_lot_camper", "building", "camperIso", "camper", "", 84f, 42f, 6f, "ground", 6, null, "StPetersCamperLot", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "structure.stp_ginny_woodshed", "building", "wharfBuilding2", "netShed", "", 93f, 34f, 6f, "ground", 3, null, "StPetersGinnyPlot", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "structure.stp_ginny_net_store", "building", "wharfBuilding2", "redShed", "", 95f, 22f, 6f, "ground", 1, null, "StPetersGinnyPlot", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "structure.stp_ginny_lean_to", "building", "wharfBuilding2", "netShed", "", 74f, 33f, 6f, "ground", 5, null, "StPetersGinnyPlot", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_gate_garden", "setPiece", "yardIso", "picketGate", "", 80.2f, 20.8f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_chair", "setPiece", "ginnyPieces", "chair", "", 77.9f, 25.6f, 6f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_lantern", "setPiece", "ginnyPieces", "lantern", "", 78.15f, 26.35f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hod_full", "setPiece", "ginnyPieces", "clamHod", "", 79f, 30f, 6f, "ground", 1, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hod", "setPiece", "ginnyPieces", "clamHod", "", 78.55f, 30.5f, 6f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_rakes", "setPiece", "ginnyPieces", "rakes", "", 79.85f, 30.4f, 6f, "ground", 6, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_freezer", "setPiece", "ginnyPieces", "chestFreezer", "", 78f, 24f, 6f, "ground", 7, null, "StPetersGinnyPlot", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_rain_barrel", "setPiece", "yardIso", "rainBarrel", "", 80.35f, 24.35f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_name_sign", "setPiece", "yardIso", "nameSign", "", 73.6f, 25.35f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] { "words.stp_ginny_sign" }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_cottage_lilac", "setPiece", "yardIso", "lilac", "", 88.8f, 23.9f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_cottage_rose", "setPiece", "yardIso", "roseBush", "", 80.6f, 32.1f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_veg_1", "setPiece", "yardIso", "vegRows", "", 84.2f, 18.4f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_veg_2", "setPiece", "yardIso", "vegRows", "", 84.2f, 14.9f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_potato", "setPiece", "yardIso", "potatoDrills", "", 88.4f, 16.6f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_rhubarb", "setPiece", "yardIso", "rhubarb", "", 77.9f, 18.9f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_raspberry", "setPiece", "yardIso", "raspberryRow", "", 90.6f, 16.8f, 6f, "ground", 2, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_border", "setPiece", "yardIso", "borderBed", "", 86.6f, 19.8f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_scarecrow", "setPiece", "ginnyPieces", "scarecrow", "", 86.3f, 16.9f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_potato_2", "setPiece", "yardIso", "potatoDrills", "", 88.4f, 13.6f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_peas", "setPiece", "yardIso", "trellisVine", "", 80.9f, 17.6f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_rhubarb_2", "setPiece", "yardIso", "rhubarb", "", 78f, 15.6f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_potting", "setPiece", "yardIso", "trapBench", "", 77.4f, 17.4f, 6f, "ground", 2, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_compost", "setPiece", "yardIso", "compostBin", "", 90.3f, 13.5f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_barrow", "setPiece", "wharfDecor", "wheelbarrow", "", 81.6f, 13.7f, 6f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_tools", "setPiece", "yardIso", "toolLean", "", 77.4f, 13.4f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_pots", "setPiece", "yardIso", "potCluster", "", 77.6f, 20.1f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_henhouse", "setPiece", "ginnyPieces", "henhouse", "", 72.9f, 20.8f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_1", "setPiece", "ginnyPieces", "hen", "", 70.3f, 18.2f, 6f, "ground", 1, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_2", "setPiece", "ginnyPieces", "hen", "", 71.8f, 17.1f, 6f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_3", "setPiece", "ginnyPieces", "hen", "", 69.2f, 20.1f, 6f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_4", "setPiece", "ginnyPieces", "hen", "", 72.6f, 18.4f, 6f, "ground", 6, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_5", "setPiece", "ginnyPieces", "hen", "", 68.7f, 16.9f, 6f, "ground", 2, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_6", "setPiece", "ginnyPieces", "hen", "", 75.7f, 24.1f, 6f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_leanto_wood", "setPiece", "yardIso", "woodpile", "", 72f, 29.5f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_leanto_stack", "setPiece", "wharfDecor", "woodStack", "", 76.6f, 30.2f, 6f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_chopping", "setPiece", "ginnyPieces", "block", "", 75.1f, 28.9f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_sawhorses", "setPiece", "yardIso", "sawhorses", "", 70f, 29.2f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_ned_buoys", "setPiece", "yardIso", "buoyPost", "", 89.9f, 31.1f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_ned_traps", "setPiece", "wharfDecor", "trapStack", "", 95.9f, 37.2f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_woodshed_stack", "setPiece", "wharfDecor", "woodStack", "", 90.4f, 35.9f, 6f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_ned_anchor", "setPiece", "wharfDecor", "anchorProp", "", 98.4f, 25.3f, 6f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_washing", "setPiece", "stpLightPieces", "clothesline", "", 91.6f, 27.3f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_camper_chair", "setPiece", "wharfDecor", "deckChair", "", 87.9f, 39.7f, 6f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_camper_boots", "setPiece", "wharfDecor", "bootRack", "", 83.4f, 40.15f, 6f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_track_cart", "setPiece", "wharfDecor", "dockCart", "", 86.6f, 47.9f, 6.01f, "ground", 1, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "boat.stp_ginny_skiff", "boat", "dory", "decor", "", 97.98f, 61.16f, 2.47f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_skiff_grapnel", "setPiece", "wharfDecor", "anchorProp", "", 100.2f, 66.9f, 0.2f, "ground", 2, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_track_staff", "setPiece", "wharfDecor", "tideStaff", "", 101.9f, 68.6f, 0.18f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "gull.stp_gp_camper", "gull", "seagull", "perch", "", 85.4f, 42.1f, 8.84f, "mount", 6, null, "", "home.ginny_lot_camper", "roof", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "gull.stp_gp_mud", "gull", "seagull", "perch", "", 110.2f, 77.9f, 1.02f, "mount", 2, null, "", "rock.stp_gp_erratic_02", "perch", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "gull.stp_gp_reef", "gull", "seagull", "perch", "", 74.6f, 84.4f, 0.11f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_garden_fence", "setPiece", "yardIso", "picketPanel", "", 77.75f, 12.5f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "prop.stp_gp_hen_run", "setPiece", "ginnyPieces", "henRun", "", 67.5f, 15.6f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_red_maple_01", "tree", "treeIsoRig4", "RedMaple", "", 71.8f, 38.8f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_white_birch_01", "tree", "treeIsoRig4", "WhiteBirch", "", 89.4f, 45.3f, 6.01f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_white_birch_02", "tree", "treeIsoRig4", "WhiteBirch", "", 90.9f, 46.8f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_balsam_fir_01", "tree", "treeIsoRig4", "BalsamFir", "", 98.2f, 37.8f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_red_oak_01", "tree", "treeIsoRig4", "RedOak", "", 100.8f, 12.8f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_white_pine_01", "tree", "treeIsoRig4", "WhitePine", "", 64.4f, 32.9f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "tree.stp_gp_trembling_aspen_01", "tree", "treeIsoRig4", "TremblingAspen", "", 66.8f, 13.3f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_wild_rose_01", "plant", "plantIsoRig5", "WildRose", "", 75.2f, 29.9f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_raspberry_01", "plant", "plantIsoRig5", "Raspberry", "", 96.6f, 17.6f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_serviceberry_01", "plant", "plantIsoRig5", "Serviceberry", "", 99.4f, 33.4f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_meadowsweet_01", "plant", "plantIsoRig5", "Meadowsweet", "", 69f, 24.1f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_steeplebush_01", "plant", "plantIsoRig5", "Steeplebush", "", 92.8f, 12.2f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_speckled_alder_01", "plant", "plantIsoRig5", "SpeckledAlder", "", 104.6f, 57.2f, 5.37f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "plant.stp_gp_sweet_gale_01", "plant", "plantIsoRig5", "SweetGale", "", 102.9f, 51.8f, 5.25f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "rock.stp_gp_erratic_01", "rock", "pxRockIso3", "erratic", "", 97.6f, 30.2f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "rock.stp_gp_perched_01", "rock", "pxRockIso3", "perched", "", 68.9f, 36.8f, 6f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ginnys_plot", "rock.stp_gp_erratic_02", "rock", "pxRockIso3", "erratic", "", 110.2f, 77.9f, 0.02f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_landing
            new Row("keyscene.stp_landing", "prop.stp_slip_tide_board", "setPiece", "stPetersSetPieces", "slipTideBoard", "", 200.9f, -3.62f, -1.75f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_harbour_vane", "setPiece", "stPetersSetPieces", "harbourVane", "", 183.6f, -4.4f, 5.96f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "structure.stp_bait_store", "building", "wharfBuilding2", "tealShack", "", 182.3f, -8.8f, 6f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] { "words.bait_store_name" }),
            new Row("keyscene.stp_landing", "station.st_peters.slip_lantern", "setPiece", "wharfDecor", "lanternPost", "", 184.5f, 0.5f, 5.35f, "deck", 4, 0.5f, "StPetersWharf.LampPostSites", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "station.st_peters.head_lamp", "setPiece", "wharfDecor", "lanternPost", "", 211.5f, 0.5f, 5.35f, "deck", 4, 0.5f, "StPetersWharf.LampPostSites", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_landing_traps", "setPiece", "wharfDecor", "trapStack", "", 187.3f, 2.05f, 5.35f, "deck", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_landing_totes", "setPiece", "wharfDecor", "toteStack", "", 190.1f, 2.2f, 5.35f, "deck", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_landing_cart", "setPiece", "wharfDecor", "dockCart", "", 193.2f, 1.5f, 5.35f, "deck", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_landing_bait_barrel", "setPiece", "wharfDecor", "baitBarrel", "", 205.9f, 2f, 5.35f, "deck", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_landing_rope", "setPiece", "wharfDecor", "ropeCoil", "", 206.5f, -2f, 5.35f, "deck", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_landing_gull", "gull", "seagull", "perch", "", 213.5f, 2.5f, 5.72f, "mount", 5, 2.4f, "", "context.wharf", "northPilehead", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_strand_bench", "setPiece", "wharfDecor", "bench", "", 186f, 17.2f, 5.86f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_wrack_driftwood", "setPiece", "shoreFinds", "Driftwood", "bleached", 198.45f, 12.4f, 2.39f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_wrack_plank", "setPiece", "shoreFinds", "DriftPlank", "dry", 197.1f, 16.4f, 2.41f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_wrack_float", "setPiece", "shoreFinds", "NetFloat", "dry", 198.95f, 10.4f, 2.42f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_wrack_rope", "setPiece", "shoreFinds", "RopeScrap", "dry", 196.2f, 18.6f, 2.41f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_landing", "prop.stp_wrack_lath", "setPiece", "shoreFinds", "TrapLath", "bleached", 197.9f, 14.3f, 2.38f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_main_beach
            new Row("keyscene.stp_main_beach", "prop.stp_beach_bench", "setPiece", "wharfDecor", "bench", "", 12.6f, -57.3f, 5.48f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_main_beach", "prop.stp_beach_steps", "setPiece", "nmcSetPieces", "gullySteps", "", 11f, -59f, 2.78f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_main_beach", "prop.stp_beach_sign", "setPiece", "wharfDecor", "noticeBoard", "", 13.9f, -56.6f, 5.18f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_ne_light
            new Row("keyscene.stp_ne_light", "station.stp_ne_light", "building", "lightStation2", "schoolhouse", "", 206.5f, 58.8f, 11f, "ground", 0, null, "", "", "", new string[] { "integral" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "station.stp_ne_light_tower", "building", "lightStation2", "pyramid", "", 206.5f, 58.8f, 11f, "ground", 0, null, "", "", "", new string[] { "tower", "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "structure.stp_ne_fog_bell", "setPiece", "stpLightPieces", "fogBell", "", 215.4f, 61.8f, 11f, "ground", 1, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_clothesline", "setPiece", "stpLightPieces", "clothesline", "", 185f, 59.6f, 11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_flagstaff", "setPiece", "wharfDecor", "flagpole", "", 199.6f, 52.4f, 11f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_woodpile", "setPiece", "wharfDecor", "woodStack", "", 192.6f, 55.2f, 11f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_woodpile_b", "setPiece", "wharfDecor", "woodStack", "", 191.3f, 55.6f, 11f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_brow_bench", "setPiece", "wharfDecor", "bench", "", 189.6f, 45.9f, 11f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_barrow", "setPiece", "wharfDecor", "wheelbarrow", "", 194.2f, 57.4f, 11f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_find_0", "setPiece", "shoreFinds", "DriftBranch", "bleached", 188.19f, 37.77f, 0.55f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_find_1", "setPiece", "shoreFinds", "NetFloat", "dry", 192.87f, 40.86f, -0.51f, "ground", 3, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_find_2", "setPiece", "shoreFinds", "RopeScrap", "dry", 189.01f, 32.16f, 2.3f, "ground", 6, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_find_3", "setPiece", "shoreFinds", "TrapLath", "bleached", 191.6f, 40.6f, -0.32f, "ground", 1, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_find_4", "setPiece", "shoreFinds", "Driftwood", "bleached", 194.4f, 42.8f, -0.05f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_find_5", "setPiece", "shoreFinds", "GullFeather", "dry", 188.38f, 36.67f, 0.82f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_stack_a", "gull", "seagull", "perch", "", 223.6f, 58.1f, 7.65f, "mount", 3, null, "", "form.stp_lantern_stack", "top", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_stack_b", "gull", "seagull", "perch", "", 224.9f, 57.6f, 7.65f, "mount", 6, null, "", "form.stp_lantern_stack", "top", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_bell", "gull", "seagull", "perch", "", 215.5f, 61.75f, 14.12f, "mount", 5, null, "", "structure.stp_ne_fog_bell", "frame", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_bar_a", "gull", "seagull", "perch", "", 233.6f, 75.2f, -0.02f, "ground", 2, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_bar_b", "gull", "seagull", "perch", "", 235.1f, 76.4f, -0.29f, "ground", 7, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_bar_c", "gull", "seagull", "perch", "", 231.8f, 73.9f, -0.03f, "ground", 4, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_face_a", "gull", "seagull", "perch", "", 199f, 46.2f, 6.4f, "mount", 4, null, "", "ground.stp_ne_head", "westFaceLedge", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_face_b", "gull", "seagull", "perch", "", 204.9f, 47.9f, 8.3f, "mount", 3, null, "", "ground.stp_ne_head", "westFaceLedge", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "prop.stp_ne_gull_face_c", "gull", "seagull", "perch", "", 210.6f, 50.2f, 4.6f, "mount", 5, null, "", "ground.stp_ne_head", "southFaceLedge", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "aid.stp_ne_bar_east_cardinal", "navMark", "navBuoyRig", "CardinalE", "", 259.8f, 105.2f, 0f, "water", 0, null, "StPetersNavMarks.Cardinals", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "structure.stp_ne_brow_fence", "setPiece", "stpLightPieces", "picket", "", 181.65f, 41.14f, 11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "structure.stp_ne_garden_fence", "setPiece", "stpLightPieces", "picket", "", 187.2f, 58f, 11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "path.stp_ne_plank", "setPiece", "stpLightPieces", "plank", "", 168.4f, 45f, 7.94f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "rock.stp_ne_fall_block", "rock", "pxRockIso3", "block", "", 191.2f, 41f, 0.11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "rock.stp_ne_fall_slab", "rock", "pxRockIso3", "slab", "", 197.9f, 44.2f, -0.07f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "rock.stp_ne_fall_cloven", "rock", "pxRockIso3", "cloven", "", 203.8f, 46f, -0.06f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "rock.stp_ne_tip_knuckle", "rock", "pxRockIso3", "knuckle", "", 220.8f, 56.8f, 0f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "rock.stp_ne_stack_skerry", "rock", "pxRockIso3", "skerry", "", 229.2f, 60.4f, -0.82f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "tree.stp_ne_keepers_spruce", "tree", "treeIsoRig4", "BlackSpruce", "", 180.4f, 56.2f, 11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "tree.stp_ne_keepers_fir", "tree", "treeIsoRig4", "BalsamFir", "", 178.6f, 54f, 11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_ne_light", "tree.stp_ne_root_spruce", "tree", "treeIsoRig4", "BlackSpruce", "", 182f, 57.9f, 11f, "ground", 0, null, "", "", "", new string[] { "today" }, new string[] {  }),
            // keyscene.stp_whelps_lookout
            new Row("keyscene.stp_whelps_lookout", "prop.stp_whelps_lookout_bench", "setPiece", "wharfDecor", "bench", "", 166.9f, -39.3f, 6f, "ground", 5, null, "", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "prop.stp_xp_gull_stack_a", "gull", "seagull", "perch", "", 191.4f, -37.4f, 6.25f, "mount", 3, -37.5f, "", "form.stp_harbour_stack", "top", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "prop.stp_xp_gull_stack_b", "gull", "seagull", "perch", "", 192.8f, -38.6f, 6.25f, "mount", 5, -38.7f, "", "form.stp_harbour_stack", "top", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "prop.stp_xp_gull_stack_c", "gull", "seagull", "perch", "", 190.7f, -38.9f, 6.2f, "mount", 4, -39f, "", "form.stp_harbour_stack", "top", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "prop.stp_xp_gull_w2_rock", "gull", "seagull", "perch", "", 192.3f, -49.6f, -1.11f, "ground", 6, -49.7f, "", "", "", new string[] { "night", "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w1_a", "wildlife", "sealIso", "haul", "", 184f, -45.1f, -1.11f, "ground", 6, null, "", "", "", new string[] { "night", "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w1_b", "wildlife", "sealIso", "banana", "", 187.9f, -46.9f, -1.25f, "ground", 1, null, "", "", "", new string[] { "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w1_c", "wildlife", "sealIso", "alert", "", 186.6f, -47.95f, -1.15f, "ground", 4, null, "", "", "", new string[] { "night", "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w2_a", "wildlife", "sealIso", "haul", "", 190.4f, -50.7f, -1.27f, "ground", 5, null, "", "", "", new string[] { "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w2_b", "wildlife", "sealIso", "side", "", 193.4f, -51f, -1.2f, "ground", 3, null, "", "", "", new string[] { "night", "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w3_a", "wildlife", "sealIso", "banana", "", 179.6f, -51.3f, -0.72f, "ground", 7, null, "", "", "", new string[] { "dawn", "golden", "night", "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w3_b", "wildlife", "sealIso", "haul", "", 182.3f, -53f, -0.9f, "ground", 2, null, "", "", "", new string[] { "night", "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w3_c", "wildlife", "sealIso", "haul", "", 179.66f, -53.34f, -0.36f, "ground", 1, null, "", "", "", new string[] { "dawn", "golden", "night", "fog", "low", "neap" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_w3_d", "wildlife", "sealIso", "banana", "", 180.83f, -53.89f, -0.56f, "ground", 5, null, "", "", "", new string[] { "dawn", "golden", "night", "fog", "low", "neap" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_in_a", "wildlife", "sealIso", "swim", "", 178.2f, -38.6f, 0f, "water", 3, null, "", "", "", new string[] { "fog", "low" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_off_a", "wildlife", "sealIso", "bottle", "", 189.4f, -54.4f, 0f, "water", 3, null, "", "", "", new string[] { "noon", "dusk", "high", "autumn" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "wildlife.stp_seal_off_b", "wildlife", "sealIso", "swim", "", 183.6f, -49.6f, 0f, "water", 6, null, "", "", "", new string[] { "noon", "dusk", "high", "autumn" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "boat.stp_dory_home", "boat", "dory", "dory", "", 196.8f, -47.2f, 0f, "water", 0, null, "", "", "", new string[] { "dusk" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_1", "rock", "pxRockIso3", "skerry", "", 186f, -46f, -1.19f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_1_b", "rock", "pxRockIso3", "knuckle", "", 184.5f, -46.9f, -1.08f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_1_c", "rock", "pxRockIso3", "shelf", "", 187.4f, -45f, -1.16f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_2", "rock", "pxRockIso3", "skerry", "", 192f, -50f, -1.14f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_2_b", "rock", "pxRockIso3", "knuckle", "", 193.2f, -49.3f, -1.22f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_3", "rock", "pxRockIso3", "skerry", "", 181f, -52f, -0.83f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_whelp_3_b", "rock", "pxRockIso3", "slab", "", 182f, -51.1f, -0.94f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
            new Row("keyscene.stp_whelps_lookout", "rock.stp_east_gap_skerry", "rock", "pxRockIso3", "skerry", "", 176.35f, -55.98f, 0.24f, "ground", 0, null, "CoastFormField (PR 5b)", "", "", new string[] { "today" }, new string[] {  }),
        };
    }
}
