using System;
using System.Collections.Generic;
using System.IO;
using HiddenHarbours.World;
using UnityEngine;

namespace HiddenHarbours.Tools.RigBaking
{
    /// <summary>
    /// <b>THE NOTEBOOK KIT'S GENERATED CONTRACT, READ BACK.</b> Loads
    /// <c>docs/art/rigs/notebook-kit/notebook.contract.json</c> and diffs it against
    /// <see cref="NotebookKit"/>.
    ///
    /// <para><b>The JSON is the oracle.</b> It is generated by the rig at its own defaults and the
    /// file says so on the tin ("MEASURED values, per-value provenance — generated, never
    /// hand-edited"). So <see cref="Disagreements"/> exists to fail the C# constants, never the file:
    /// if the two part, the constant is wrong. <see cref="NotebookKitBaker"/> calls it before a single
    /// pixel is written, because a bake measured against the wrong ruler produces art that looks fine
    /// and is subtly the wrong size.</para>
    ///
    /// <para>The layout formulae are checked by REGENERATION rather than by reading: every row of the
    /// kit's own 20-row ladder is recomputed from <see cref="NotebookKit"/>'s functions and compared.
    /// A formula that agrees with the kit at 20 points across the whole legal range is not a
    /// transcription, it is the same formula.</para>
    /// </summary>
    public sealed class NotebookKitContract
    {
        public const string KitFolder = "docs/art/rigs/notebook-kit";
        public const string ContractFileName = "notebook.contract.json";

        // ---- the shapes JsonUtility fills ------------------------------------------------------

        [Serializable] public class GridBlock { public int ppu; }

        [Serializable]
        public class CellBlock
        {
            public int adv, w, box, cap, xh, desc, baseline, line, leading, slack, rule, pitch;
            public int[] glyph;
            public string from;
        }

        [Serializable]
        public class LanesBlock { public int padL, cursor, box, boxSize, padR, marginRuleAt; }

        [Serializable]
        public class GeoBlock
        {
            public int coverPad, edge, gutter, tabCol, padL, padR, cursorLane, boxLane, box,
                       ruleInset, headH, padB, pitch, sq, tabH, tabGap, tabTop, maxTabs, tabPad,
                       minCols, maxCols, minLines, maxLines, maxScale, ribbonW, plateMinLines;
        }

        [Serializable] public class SizeBlock { public int cols, lines; public int[] px; }

        [Serializable] public class CaretBlock { public int w, h; public int[] cell; }

        [Serializable]
        public class LadderRow
        {
            public int cols, lines, titleCols, cellsPerSpread;
            public int[] spreadPx, pagePx, atScale2, atScale3;
            public float[] metres;
        }

        [Serializable]
        public class TypeBlock
        {
            public CellBlock cell;
            public LanesBlock lanes;
            public GeoBlock geo;
            public SizeBlock min, max;
            public CaretBlock caret;
            public LadderRow[] ladder;
        }

        [Serializable] public class ChipBlock { public int w, h, pad, gap, top, max; }
        [Serializable] public class TabsBlock { public ChipBlock chip; }

        [Serializable]
        public class SheetEntry
        {
            public string piece, note;
            public int[] px, crop;
        }

        [Serializable]
        public class Root
        {
            public string kit;
            public int version;
            public GridBlock grid;
            public TypeBlock type;
            public TabsBlock tabs;
            public SheetEntry[] sheet;
        }

        public Root Data { get; }
        public string SourcePath { get; }

        NotebookKitContract(Root data, string path) { Data = data; SourcePath = path; }

        public static NotebookKitContract Load(string repoRoot = null)
        {
            string root = repoRoot ?? RigCatalog.RepoRoot;
            string full = Path.Combine(root, KitFolder, ContractFileName);
            if (!File.Exists(full))
                throw new FileNotFoundException(
                    $"The notebook kit's contract is missing at {full}. The kit is committed under " +
                    $"{KitFolder}/ — if this fired, the branch predates that import.", full);

            var data = JsonUtility.FromJson<Root>(File.ReadAllText(full));
            if (data?.grid == null || data.type?.cell == null || data.type.geo == null ||
                data.sheet == null || data.sheet.Length == 0)
                throw new InvalidOperationException(
                    $"{full} parsed but came back without its grid/type/geo/sheet blocks. The " +
                    "contract changed shape — fix this reader rather than the file, which is generated.");

            return new NotebookKitContract(data, full);
        }

        // ---- lookups -----------------------------------------------------------------------------

        /// <summary>The reference-sheet row for a piece key, or null if the kit does not list it.</summary>
        public SheetEntry SheetPiece(string key)
        {
            foreach (var e in Data.sheet)
                if (string.Equals(e.piece, key, StringComparison.Ordinal)) return e;
            return null;
        }

        // ---- the oracle ---------------------------------------------------------------------------

        /// <summary>
        /// Every place <see cref="NotebookKit"/> disagrees with the generated contract. Empty is the
        /// only acceptable answer; the baker refuses to run otherwise.
        /// </summary>
        public List<string> Disagreements()
        {
            var bad = new List<string>();
            void Eq(string what, int mine, int theirs)
            {
                if (mine != theirs) bad.Add($"{what}: C# says {mine}, the contract says {theirs}");
            }

            Eq("grid.ppu", NotebookKit.PixelsPerUnit, Data.grid.ppu);

            var c = Data.type.cell;
            Eq("cell.adv", NotebookKit.CellWidth, c.adv);
            Eq("cell.line", NotebookKit.CellHeight, c.line);
            Eq("cell.w (glyph)", NotebookKit.GlyphWidth, c.w);
            Eq("cell.box (glyph)", NotebookKit.GlyphHeight, c.box);
            Eq("cell.baseline", NotebookKit.BaselineRow, c.baseline);
            Eq("cell.leading", NotebookKit.Leading, c.leading);
            Eq("cell.pitch", NotebookKit.Pitch, c.pitch);
            Eq("cell.rule", NotebookKit.RuleRow, c.rule);
            Eq("cell.slack", NotebookKit.Slack, c.slack);

            var g = Data.type.geo;
            Eq("geo.padL", NotebookKit.PadL, g.padL);
            Eq("geo.padR", NotebookKit.PadR, g.padR);
            Eq("geo.padB", NotebookKit.PadB, g.padB);
            Eq("geo.cursorLane", NotebookKit.CursorLane, g.cursorLane);
            Eq("geo.boxLane", NotebookKit.BoxLane, g.boxLane);
            Eq("geo.box", NotebookKit.BoxSize, g.box);
            Eq("geo.headH", NotebookKit.HeadHeight, g.headH);
            Eq("geo.ruleInset", NotebookKit.RuleInset, g.ruleInset);
            Eq("geo.coverPad", NotebookKit.CoverPad, g.coverPad);
            Eq("geo.edge", NotebookKit.Edge, g.edge);
            Eq("geo.gutter", NotebookKit.Gutter, g.gutter);
            Eq("geo.tabCol", NotebookKit.TabCol, g.tabCol);
            Eq("geo.tabH", NotebookKit.TabHeight, g.tabH);
            Eq("geo.tabPad", NotebookKit.TabPad, g.tabPad);
            Eq("geo.tabGap", NotebookKit.TabGap, g.tabGap);
            Eq("geo.tabTop", NotebookKit.TabTop, g.tabTop);
            Eq("geo.maxTabs", NotebookKit.MaxTabs, g.maxTabs);
            Eq("geo.ribbonW", NotebookKit.RibbonWidth, g.ribbonW);
            Eq("geo.plateMinLines", NotebookKit.PlateMinLines, g.plateMinLines);
            Eq("geo.minCols", NotebookKit.MinCols, g.minCols);
            Eq("geo.maxCols", NotebookKit.MaxCols, g.maxCols);
            Eq("geo.minLines", NotebookKit.MinLines, g.minLines);
            Eq("geo.maxLines", NotebookKit.MaxLines, g.maxLines);
            Eq("geo.maxScale", NotebookKit.MaxScale, g.maxScale);

            if (Data.tabs?.chip != null)
            {
                Eq("tabs.chip.w", NotebookKit.TabChipWidth, Data.tabs.chip.w);
                Eq("tabs.chip.h", NotebookKit.TabHeight, Data.tabs.chip.h);
                Eq("tabs.chip.max", NotebookKit.MaxTabs, Data.tabs.chip.max);
            }

            if (Data.type.caret != null)
            {
                Eq("caret.w", DialogueBubbleKit.CaretWidth, Data.type.caret.w);
                Eq("caret.h", DialogueBubbleKit.CaretHeight, Data.type.caret.h);
            }

            // ---- the ladder, REGENERATED rather than read ------------------------------------------
            var ladder = Data.type.ladder;
            if (ladder == null || ladder.Length == 0)
            {
                bad.Add("type.ladder is empty — the formulae would then be checked against nothing, " +
                        "which is the vacuous green this oracle exists to prevent");
            }
            else
            {
                foreach (var r in ladder)
                {
                    string at = $"ladder[{r.cols}×{r.lines}]";
                    Eq($"{at}.titleCols", NotebookKit.TitleColsFor(r.cols), r.titleCols);
                    Eq($"{at}.cellsPerSpread", NotebookKit.CellsPerSpread(r.cols, r.lines), r.cellsPerSpread);

                    if (r.spreadPx is { Length: 2 })
                    {
                        Eq($"{at}.spreadPx.w", NotebookKit.SpreadWidthFor(r.cols), r.spreadPx[0]);
                        Eq($"{at}.spreadPx.h", NotebookKit.SpreadHeightFor(r.lines), r.spreadPx[1]);
                    }
                    if (r.pagePx is { Length: 2 })
                    {
                        Eq($"{at}.pagePx.w", NotebookKit.PageWidthFor(r.cols), r.pagePx[0]);
                        Eq($"{at}.pagePx.h", NotebookKit.PageHeightFor(r.lines), r.pagePx[1]);
                    }
                    if (r.atScale2 is { Length: 2 })
                    {
                        Eq($"{at}.atScale2.w", NotebookKit.SpreadWidthFor(r.cols) * 2, r.atScale2[0]);
                        Eq($"{at}.atScale2.h", NotebookKit.SpreadHeightFor(r.lines) * 2, r.atScale2[1]);
                    }
                    if (r.atScale3 is { Length: 2 })
                    {
                        Eq($"{at}.atScale3.w", NotebookKit.SpreadWidthFor(r.cols) * 3, r.atScale3[0]);
                        Eq($"{at}.atScale3.h", NotebookKit.SpreadHeightFor(r.lines) * 3, r.atScale3[1]);
                    }
                }
            }

            // ---- every baked piece must be measurable ----------------------------------------------
            foreach (var piece in NotebookKit.Pieces)
                if (SheetPiece(SheetKeyFor(piece)) == null)
                    bad.Add($"{piece} maps to sheet key '{SheetKeyFor(piece)}', which the contract " +
                            "does not list — the bake would have nothing to check its size against");

            return bad;
        }

        /// <summary>
        /// The kit's reference-sheet key for one of our asset names — <c>Notebook_Box_Pencil</c> →
        /// <c>box.pencil</c>. Derived rather than tabulated so a new piece cannot be added with a
        /// silently wrong key.
        /// </summary>
        public static string SheetKeyFor(string pieceName)
        {
            string s = pieceName.StartsWith("Notebook_", StringComparison.Ordinal)
                ? pieceName.Substring("Notebook_".Length)
                : pieceName;
            int u = s.IndexOf('_');
            return (u < 0 ? s : s.Substring(0, u) + "." + s.Substring(u + 1)).ToLowerInvariant();
        }
    }
}
